CREATE DATABASE sql_test;

USE sql_test;

/**
 * 2: Create agents table
 */

CREATE TABLE AGENTS (
    AGENT_CODE CHAR(6) PRIMARY KEY NOT NULL,
    AGENT_NAME CHAR(40) NOT NULL,
    WORKING_AREA CHAR(35),
    COMMISSION DECIMAL(10, 2),
    PHONE_NO CHAR(15) NOT NULL,
    COUNTRY VARCHAR(25)
);

/**
 * 3: Create customer table
 */

CREATE TABLE CUSTOMER(
    CUST_CODE VARCHAR(6) PRIMARY KEY NOT NULL,
    CUST_NAME VARCHAR(40) NOT NULL,
    CUST_CITY CHAR(35),
    WORKING_AREA VARCHAR(35),
    CUST_CONTRY VARCHAR(20),
    GRADE INT,
    OPENING_AMT DECIMAL(12, 2),
    RECEIVE_AMT DECIMAL(12, 2),
    PAYMENT_AMT DECIMAL(12, 2),
    OUTSTANDING_AMT DECIMAL(12, 2),
    PHONE_NO VARCHAR(17),
    AGENT_CODE VARCHAR(6),
    FOREIGN KEY (AGENT_CODE) REFERENCES AGENTS(AGENT_CODE)
);

/**
 * 4: Create orders table
 */

CREATE TABLE ODERS(
    ORD_NUM DECIMAL(6, 0),
    ORD_AMOUNT DECIMAL(12, 2) NOT NULL,
    ADVANCED_AMOUT DECIMAL(12, 2),
    ORD_DATE DATE NOT NULL,
    ORD_DESCRIPTION VARCHAR(60),
    CUST_CODE VARCHAR(6),
    AGENT_CODE CHAR(6),
    FOREIGN KEY (CUST_CODE) REFERENCES CUSTOMER(CUST_CODE),
    FOREIGN KEY (AGENT_CODE) REFERENCES AGENTS(AGENT_CODE)
)